<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/mdview.Infrastructure/mdview.Infrastructure.csproj" />
  </ItemGroup>
</Project>
